# Generated by Django 4.1.5 on 2023-03-09 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='orgBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_created_date', models.DateTimeField(auto_created=True)),
                ('organization_id', models.PositiveBigIntegerField()),
                ('company_name', models.CharField(max_length=100)),
                ('language_code', models.CharField(max_length=12)),
                ('time_zone', models.CharField(max_length=100)),
                ('is_org_active', models.BooleanField()),
                ('price_precision', models.SmallIntegerField()),
                ('address', models.TextField(max_length=300)),
                ('description', models.TextField(max_length=300)),
                ('employee_count', models.PositiveIntegerField()),
                ('website', models.URLField()),
                ('primary_email', models.EmailField(max_length=254)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
