# Generated by Django 4.1.5 on 2023-02-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dynamic_tables',
            fields=[
                ('table_name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('proto_name', models.TextField(max_length=150)),
            ],
        ),
    ]
