# Generated by Django 4.1.5 on 2023-03-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '00KP_09'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='jelo',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
