# Generated by Django 4.1.5 on 2023-02-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='ert1',
            new_name='ert',
        ),
    ]
