# Generated by Django 4.1.5 on 2023-03-01 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0014_rename_ert1_good_ert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='ert',
            new_name='ert1',
        ),
    ]
