# Generated by Django 4.1.4 on 2023-01-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kv_creds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoho_user_name', models.EmailField(max_length=254)),
                ('zoho_user_pwd', models.TextField(max_length=30)),
                ('zoho_org_id', models.TextField(max_length=100)),
            ],
        ),
    ]
