# Generated by Django 4.1.4 on 2023-01-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kv_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kv_creds',
            name='zoho_org_domain',
            field=models.TextField(default='.in', max_length=10),
        ),
    ]
