# Generated by Django 4.1.4 on 2023-01-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kv_report', '0003_billitem_transactions_positive_warehousetotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousetotal',
            name='status_formatted',
        ),
    ]
