# Generated by Django 4.1.4 on 2023-01-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kv_report', '0004_remove_warehousetotal_status_formatted'),
    ]

    operations = [
        migrations.CreateModel(
            name='warehouse_total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveBigIntegerField()),
                ('warehouse_status', models.PositiveBigIntegerField()),
                ('quantity_sold', models.FloatField()),
                ('quantity_ordered', models.FloatField()),
                ('warehouse_name', models.TextField(max_length=50)),
                ('is_primary_warehouse', models.BooleanField()),
                ('quantity_available_for_sale', models.FloatField()),
                ('quantity_demanded', models.FloatField()),
                ('quantity_purchased', models.FloatField()),
                ('warehouse_id', models.PositiveBigIntegerField()),
                ('quantity_available', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='warehouseTotal',
        ),
    ]
