# Generated by Django 4.1.4 on 2023-01-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kv_report', '0005_warehouse_total_delete_warehousetotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse_total',
            name='warehouse_status',
            field=models.TextField(max_length=50),
        ),
    ]
