# Generated by Django 4.1.4 on 2023-01-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kv_report', '0007_transactions_psve_delete_transactions_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions_psve',
            name='item_name',
            field=models.TextField(default='1', max_length=150),
            preserve_default=False,
        ),
    ]
