# Generated by Django 4.1.4 on 2023-01-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kv_report', '0008_transactions_psve_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill_fetches',
            fields=[
                ('bill_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('bill_date', models.DateTimeField()),
            ],
        ),
    ]
