# Generated by Django 4.1.4 on 2023-01-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kv_report', '0009_bill_fetches'),
    ]

    operations = [
        migrations.CreateModel(
            name='tran_psve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveBigIntegerField()),
                ('qty_inwards', models.FloatField()),
                ('cost_price', models.FloatField()),
                ('warehouse_id', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='bill_fetches',
        ),
        migrations.DeleteModel(
            name='billItem',
        ),
        migrations.DeleteModel(
            name='transactions_psve',
        ),
        migrations.DeleteModel(
            name='warehouse_total',
        ),
    ]
