# Generated by Django 4.1.4 on 2023-01-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kv_report', '0011_tran_psve_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tran_psve',
            name='warehouse_id',
            field=models.TextField(max_length=150),
        ),
    ]
