# Generated by Django 4.1.4 on 2023-01-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kv_report', '0012_alter_tran_psve_warehouse_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tran_psve',
            name='warehouse_id',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
