# Generated by Django 4.1.4 on 2023-01-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kv_report', '0013_alter_tran_psve_warehouse_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tran_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transfer_order', models.TextField(max_length=30)),
                ('status', models.TextField(max_length=30)),
                ('item_Name', models.TextField(max_length=150)),
                ('product_id', models.PositiveBigIntegerField()),
                ('quantity_transferred', models.FloatField()),
                ('cost_price', models.FloatField()),
                ('from_warehouse_name', models.TextField(max_length=150)),
                ('to_warehouse_name', models.TextField(max_length=150)),
            ],
        ),
    ]
