# Generated by Django 4.1.5 on 2023-02-05 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ECOM_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECOM_registers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ECOM_model_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECOM_users.ecom_registers')),
            ],
        ),
    ]
