# Generated by Django 4.1.5 on 2023-02-05 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ECOM_users', '0002_ecom_registers_ecom_model_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecom_model_register',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
