# Generated by Django 4.1.5 on 2023-02-05 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ECOM_users', '0004_user_addition_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_addition_instruction',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', unique=True),
        ),
    ]
