# Generated by Django 4.1.5 on 2023-02-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECOM_users', '0005_alter_user_addition_instruction_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_addition_instruction',
            old_name='instrunction',
            new_name='instruction',
        ),
        migrations.AddField(
            model_name='user_addition_instruction',
            name='remove_instructions',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
