# Generated by Django 4.1.5 on 2023-03-09 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='geoCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_base.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_base.countries')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_base.currency')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_base.state')),
                ('zip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_base.zip')),
            ],
        ),
    ]
