# Generated by Django 4.1.5 on 2023-01-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='application_setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_key', models.UUIDField(auto_created=True)),
                ('application_name', models.TextField(max_length=50)),
            ],
        ),
    ]
