# Generated by Django 4.1.5 on 2023-01-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_application_setup_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_setup',
            name='application_name',
            field=models.CharField(max_length=50),
        ),
    ]
