# Generated by Django 4.1.5 on 2023-01-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_application_setup_application_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_setup',
            name='application_key',
            field=models.UUIDField(auto_created=True, null=True),
        ),
    ]
