# Generated by Django 4.1.5 on 2023-03-15 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_setup', '0003_rename_currency_name_currency_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='geoCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_setup.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_setup.countries')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_setup.currency')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_setup.state')),
                ('zip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_setup.zip')),
            ],
        ),
    ]
