# Generated by Django 4.1.5 on 2023-03-20 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_setup__org_prof__CustomerLevel', '0005_org_model_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='org_model',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='org_model',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='org_model',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='org_model',
            name='updated_time',
            field=models.DateTimeField(auto_now_add=True, default="2020-12-12 00:00:00"),
            preserve_default=False,
        ),
    ]
