# Generated by Django 4.1.5 on 2023-03-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_setup__org_prof__CustomerLevel', '0006_org_model_created_by_org_model_created_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='org_model',
        ),
    ]
