# Generated by Django 4.1.5 on 2023-03-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='zip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('area_allocated', models.CharField(max_length=100)),
                ('enabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField()),
                ('_chlds_included', models.ManyToManyField(to='basic_setup.city')),
            ],
        ),
        migrations.CreateModel(
            name='currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=100)),
                ('currency_numeric_code', models.CharField(max_length=10)),
                ('currency_short_code', models.CharField(max_length=3)),
                ('price_precision', models.SmallIntegerField()),
                ('enabled', models.BooleanField()),
                ('_chlds_included', models.ManyToManyField(to='basic_setup.state')),
            ],
        ),
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField()),
                ('_chlds_included', models.ManyToManyField(to='basic_setup.currency')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='_chlds_included',
            field=models.ManyToManyField(to='basic_setup.zip'),
        ),
    ]
