# Generated by Django 4.1.5 on 2023-03-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='_chlds_included',
            field=models.ManyToManyField(blank=True, null=True, to='basic_setup.zip'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='_chlds_included',
            field=models.ManyToManyField(blank=True, null=True, to='basic_setup.currency'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='_chlds_included',
            field=models.ManyToManyField(blank=True, null=True, to='basic_setup.state'),
        ),
        migrations.AlterField(
            model_name='state',
            name='_chlds_included',
            field=models.ManyToManyField(blank=True, null=True, to='basic_setup.city'),
        ),
    ]
