# Generated by Django 4.1.5 on 2023-03-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_setup', '0003_rename_currency_name_currency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='_chlds_included',
            field=models.ManyToManyField(blank=True, to='basic_setup.zip'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='_chlds_included',
            field=models.ManyToManyField(blank=True, to='basic_setup.currency'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='_chlds_included',
            field=models.ManyToManyField(blank=True, to='basic_setup.state'),
        ),
        migrations.AlterField(
            model_name='state',
            name='_chlds_included',
            field=models.ManyToManyField(blank=True, to='basic_setup.city'),
        ),
    ]
