# Generated by Django 4.1.5 on 2023-03-17 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_setup', '0004_alter_city__chlds_included_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='_prnts_associated',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='basic_setup.state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countries',
            name='_prnts_associated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_setup.countries'),
        ),
        migrations.AddField(
            model_name='currency',
            name='_prnts_associated',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='basic_setup.countries'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='_prnts_associated',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='basic_setup.countries'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zip',
            name='_prnts_associated',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='basic_setup.city'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='time_zones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time_diff_min', models.FloatField(default=0)),
                ('_chlds_included', models.ManyToManyField(blank=True, to='basic_setup.state')),
                ('_prnts_associated', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='basic_setup.countries')),
            ],
        ),
    ]
