# Generated by Django 4.1.5 on 2023-03-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_setup', '0005_city__prnts_associated_countries__prnts_associated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='_prnts_associated',
        ),
        migrations.RemoveField(
            model_name='countries',
            name='_prnts_associated',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='_prnts_associated',
        ),
        migrations.RemoveField(
            model_name='state',
            name='_prnts_associated',
        ),
        migrations.RemoveField(
            model_name='time_zones',
            name='_prnts_associated',
        ),
        migrations.RemoveField(
            model_name='zip',
            name='_prnts_associated',
        ),
    ]
