# Generated by Django 4.1.5 on 2023-03-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_setup', '0006_remove_city__prnts_associated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_zones',
            name='difference',
            field=models.CharField(default='', max_length=100),
        ),
    ]
