# Generated by Django 4.1.5 on 2023-03-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_setup', '0007_time_zones_difference'),
    ]

    operations = [
        migrations.CreateModel(
            name='date_time_format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formats', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='time_zones',
            name='difference',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
