# Generated by Django 4.1.5 on 2023-03-20 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_setup__org_prof', '0002_org_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_model',
            name='org_id',
            field=models.PositiveBigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='org_users',
            name='org',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basic_setup__org_prof.org_model'),
        ),
    ]
