# Generated by Django 4.1.5 on 2023-01-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECOM_pincodes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pincodes',
            new_name='ECOM_pincodes',
        ),
    ]
