# Generated by Django 4.1.5 on 2023-01-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECOM_pincodes', '0002_rename_pincodes_ecom_pincodes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ECOM_pincodes',
        ),
    ]
