# Generated by Django 4.1.5 on 2023-01-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ECOM_pincodes', '0003_delete_ecom_pincodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECOM_pincodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(max_length=30)),
                ('city_type', models.TextField(max_length=12)),
                ('pincode', models.TextField(max_length=6)),
                ('active', models.BooleanField()),
                ('state_code', models.TextField(max_length=6)),
                ('city', models.TextField(max_length=40)),
                ('dccode', models.TextField(max_length=40)),
                ('route', models.TextField(max_length=100)),
                ('state', models.TextField(max_length=100)),
                ('date_of_discontinuance', models.DateField(blank=True, null=True)),
                ('city_code', models.TextField(max_length=12)),
            ],
        ),
    ]
