# Generated by Django 4.1.5 on 2023-01-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECOM_pincodes', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecom_pincodes',
            name='master_vendor',
            field=models.TextField(default='2', max_length=130),
            preserve_default=False,
        ),
    ]
