# Generated by Django 4.1.5 on 2023-02-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECOM_pincodes', '0006_alter_ecom_pincodes_master_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecom_pincodes',
            name='master_vendor',
        ),
        migrations.AddField(
            model_name='ecom_pincodes',
            name='item_unqiue',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
