# Generated by Django 4.1.5 on 2023-02-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECOM_pincodes', '0007_remove_ecom_pincodes_master_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecom_pincodes',
            name='city_type',
            field=models.TextField(blank=True, max_length=12, null=True),
        ),
    ]
