# Generated by Django 4.1.5 on 2023-03-03 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BI_organisations_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='F_organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=150)),
                ('mc_status', models.BooleanField(default=False)),
                ('domain_name', models.CharField(max_length=30)),
                ('street', models.TextField(max_length=50)),
                ('employee_count', models.PositiveIntegerField()),
                ('website', models.URLField()),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('primary_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='FR_cities_allowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='FR_countries_allowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('iso_code', models.CharField(max_length=15)),
                ('country_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='FR_currencies_allowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=3)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.fr_countries_allowed')),
            ],
        ),
        migrations.CreateModel(
            name='FR_states_allowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.fr_countries_allowed')),
            ],
        ),
        migrations.CreateModel(
            name='FR_timezones_allowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=70)),
            ],
        ),
        migrations.DeleteModel(
            name='good',
        ),
        migrations.AddField(
            model_name='fr_cities_allowed',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.fr_countries_allowed'),
        ),
        migrations.AddField(
            model_name='fr_cities_allowed',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.fr_states_allowed'),
        ),
        migrations.AddField(
            model_name='f_organisation',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.fr_cities_allowed'),
        ),
        migrations.AddField(
            model_name='f_organisation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.fr_countries_allowed'),
        ),
        migrations.AddField(
            model_name='f_organisation',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisations.fr_currencies_allowed'),
        ),
        migrations.AddField(
            model_name='f_organisation',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.fr_states_allowed'),
        ),
        migrations.AddField(
            model_name='f_organisation',
            name='time_zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisations.fr_timezones_allowed'),
        ),
        migrations.AddField(
            model_name='bi_organisations_users',
            name='organisations',
            field=models.ManyToManyField(to='organisations.f_organisation'),
        ),
        migrations.AddField(
            model_name='bi_organisations_users',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
